export const generosDeLivros = [
    "Ficção Científica",
    "Fantasia",
    "Mistério",
    "Thriller",
    "Romance",
    "História",
    "Biografia",
    "Autoajuda",
    "Desenvolvimento Pessoal",
    "Filosofia",
    "Ciências",
    "Tecnologia",
    "Economia",
    "Política",
    "Cultura Pop",
    "Quadrinhos",
    "Graphic Novel",
    "Horror",
    "Literatura Infantil",
    "Young Adult",
    "Poesia",
    "Clássicos",
    "Contos",
    "Drama",
    "Aventura",
    "Espiritualidade",
    "Saúde",
    "Viagem",
    "Culinária",
    "Esportes",
    "Educação"
  ];
  