export const generosDeLivros = [
    "Ficção Científica",
    "Ficção",
    "Fantasia",
    "Mistério",
    "Sátira",
    "Thriller",
    "Romance",
    "História",
    "Biografia",
    "Educação Financeira",
    "Autoajuda",
    "Desenvolvimento Pessoal",
    "Filosofia",
    "Ciências",
    "Tecnologia",
    "Economia",
    "Política",
    "Cultura Pop",
    "Quadrinhos",
    "Graphic Novel",
    "Horror",
    "Literatura Infantil",
    "Young Adult",
    "Poesia",
    "Clássicos",
    "Contos",
    "Drama",
    "Aventura",
    "Espiritualidade",
    "Saúde",
    "Viagem",
    "Culinária",
    "Esportes",
    "Educação"
  ];
  